name: CI Windows (JUCE + VST3)

on:
  push:
    branches: [ main, develop, feature/**, fix/** ]
  pull_request:
  workflow_dispatch:
  create:
    tags:
      - 'v*'

jobs:
  build-win:
    runs-on: windows-latest

    env:
      BUILD_TYPE: RelWithDebInfo
      GENERATOR: "Visual Studio 17 2022"
      ARCH: x64
      # Optionally set this in repo variables or secrets to run pluginval
      # Example: PLUGINVAL_PATH: C:\tools\pluginval\pluginval.exe
      PLUGINVAL_PATH: ${{ vars.PLUGINVAL_PATH || secrets.PLUGINVAL_PATH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ env.ARCH }}

      - name: Configure (CMake)
        run: >
          cmake -S . -B build
          -G "${{ env.GENERATOR }}"
          -A ${{ env.ARCH }}
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build (CMake)
        run: cmake --build build --config ${{ env.BUILD_TYPE }} --parallel

      - name: Locate VST3 artefact
        id: find_vst3
        shell: pwsh
        run: |
          $p = Get-ChildItem -Recurse -File "build\*\*\VST3\*.vst3" | Select-Object -First 1
          if (!$p) { Write-Error "VST3 not found"; exit 1 }
          echo "vst3_path=$($p.FullName)" >> $env:GITHUB_OUTPUT

      - name: Upload VST3 artefact
        uses: actions/upload-artifact@v4
        with:
          name: SpectralCanvasPro-vst3-${{ env.BUILD_TYPE }}
          path: ${{ steps.find_vst3.outputs.vst3_path }}

      - name: Run pluginval (strictness 4 on push/PR)
        if: ${{ env.PLUGINVAL_PATH != '' && (github.event_name == 'push' || github.event_name == 'pull_request') }}
        shell: pwsh
        run: |
          & "${{ env.PLUGINVAL_PATH }}" --strictness 4 --verbose --validate-in-process --file "${{ steps.find_vst3.outputs.vst3_path }}"

      - name: Run pluginval (strictness 6 on tag)
        if: ${{ env.PLUGINVAL_PATH != '' && startsWith(github.ref, 'refs/tags/v') }}
        shell: pwsh
        run: |
          & "${{ env.PLUGINVAL_PATH }}" --strictness 6 --verbose --validate-in-process --file "${{ steps.find_vst3.outputs.vst3_path }}"